version: "3"
services:
  mongo:
    image: "mongo"
    networks:
      - "mongo"
    volumes:
      - "${MONGO_STORAGE:-../db:/data/db}"
    restart: "always"
  elections:
    image: "node:18"
    depends_on:
      - "mongo"
    networks:
      - "mongo"
    ports: 
      - "4000:4000"
    volumes:
      - "../:/mnt/"
    working_dir: "/mnt/backend"
    restart: "always"
    command: ["npm", "run", "start:prod"]
networks:
  mongo: